// Test class for the DMLLeadWebServiceHelperClass class.
@isTest
private class DMLLeadWebServiceClassTest {
 public  static testMethod void UnitTest() { 
     DMLLeadWebServiceClass dw= new DMLLeadWebServiceClass();
 }

/*
        public  static testMethod void UnitTest() { 
       
       DMLLeadWebServiceClass.LeadInfo lf = new DMLLeadWebServiceClass.LeadInfo();
       DMLLeadWebServiceClass.LeadInfo lf2 = new DMLLeadWebServiceClass.LeadInfo();
       DMLLeadWebServiceClass.LeadInfo lf3 = new DMLLeadWebServiceClass.LeadInfo();
          
        
       lf.lead_First_Name = 'Test lead';
       lf.lead_Last_Name = 'Last lead';
       lf.status = 'Prospect';
       lf.area_Of_Interest = 'NON GAME';
       lf.business_Type = 'Publisher';
       //lf.lead_Id ='01pK0000000AvnQ';
       lf.lead_Accepted_Id = 100;
       lf.company = 'TestCompany';
       lf.company_Address_Line1 = 'Test lane';
       lf.company_Address_Line2 = 'suite # 10';
       lf.company_Address_Line3 = '';
       lf.company_City = 'Test';
       lf.company_Country = 'Test';
       lf.company_Fax = '1111111';
       lf.company_Number_Employee = 4;
       lf.company_Phone_Number = '111111';
       lf.company_Post_Code = '94086';
       lf.company_State = 'CA';
       lf.company_Website_Address = 'Test.com';
       lf.contact_Email = 'Test@test.com';
       lf.contact_Fax_No = '1111';
       lf.contact_Job_Title = 'Director';
       lf.contact_Phone_No = '1111';
       lf.platforms = 'PS3,PS4,PSVita';
       lf.legal_Director_Name = 'Test';
       lf.legal_status = 'None';
       lf.secondary_Contact_Email ='Test@test.com';
       lf.secondary_Contact_FaxNo = '11111';
       lf.secondary_Contact_First_Name = 'Test';
       lf.secondary_Contact_Last_Name = 'contact';
       lf.Secondary_Contact_Phone_No = '1111111';
       lf.Secondary_Contact_Job_Title = 'Director';
       
       DMLLeadWebServiceClass.RequestClass req = new DMLLeadWebServiceClass.RequestClass();
         req.leadsInfo = new List<DMLLeadWebServiceClass.LeadInfo>();
      
       lf.Enquiry_Status = 'Accepted';
       lf.Media_Type = 'Digital';
       
        req.leadsInfo.add(lf);
        
       
       lf2.lead_First_Name = 'Test lead1';
       lf2.lead_Last_Name = 'Last lead2';
       lf2.status = 'Prospect';
       lf2.area_Of_Interest = 'TOOLS';
       lf.business_Type = 'Publisher';
       //lf.lead_Id ='01pK0000000AvnQ';
       lf2.lead_Accepted_Id = 200;
       lf2.company = 'TestCompany';
       lf2.company_Address_Line1 = 'Test lane';
       lf2.company_Address_Line2 = 'suite # 10';
       lf2.company_Address_Line3 = '';
       lf2.company_City = 'Test';
       lf2.company_Country = 'Test';
       lf2.company_Fax = '1111111';
       lf2.company_Number_Employee = 4;
       lf2.company_Phone_Number = '111111';
       lf2.company_Post_Code = '94086';
       lf2.company_State = 'CA';
       lf2.company_Website_Address = 'Test.com';
       lf2.contact_Email = 'Test@test.com';
       lf2.contact_Fax_No = '1111';
       lf2.contact_Job_Title = 'Director';
       lf2.contact_Phone_No = '1111';
       lf2.platforms = 'PS4';
       lf2.legal_Director_Name = 'Test';
       lf2.legal_status = 'None';
       lf2.secondary_Contact_Email ='Test@test.com';
       lf2.secondary_Contact_FaxNo = '11111';
       lf2.secondary_Contact_First_Name = 'Test';
       lf2.secondary_Contact_Last_Name = 'contact';
       lf2.Secondary_Contact_Phone_No = '1111111';
       lf2.Secondary_Contact_Job_Title = 'Director';
       
       lf2.Enquiry_Status = 'Accepted';
       lf2.Media_Type = 'Digital';
       
       req.leadsInfo.add(lf2);
       
       lf3.lead_First_Name = 'Test lead';
       lf3.lead_Last_Name = 'Last lead';
       lf3.status = 'Prospect';
       lf3.area_Of_Interest = 'GAME';
       lf3.business_Type = 'Publisher';
       //lf.lead_Id ='01pK0000000AvnQ';
       lf3.lead_Accepted_Id = 100;
       lf3.company = 'TestCompany';
       lf3.company_Address_Line1 = 'Test lane';
       lf3.company_Address_Line2 = 'suite # 10';
       lf3.company_Address_Line3 = '';
       lf3.company_City = 'Test';
       lf3.company_Country = 'Test';
       lf3.company_Fax = '1111111';
       lf3.company_Number_Employee = 4;
       lf3.company_Phone_Number = '111111';
       lf3.company_Post_Code = '94086';
       lf3.company_State = 'CA';
       lf3.company_Website_Address = 'Test.com';
       lf3.contact_Email = 'Test@test.com';
       lf3.contact_Fax_No = '1111';
       lf3.contact_Job_Title = 'Director';
       lf3.contact_Phone_No = '1111';
       lf3.platforms = 'PSVita';
       lf3.legal_Director_Name = 'Test';
       lf3.legal_status = 'None';
       lf3.secondary_Contact_Email ='Test@test.com';
       lf3.secondary_Contact_FaxNo = '11111';
       lf3.secondary_Contact_First_Name = 'Test';
       lf3.secondary_Contact_Last_Name = 'contact';
       lf3.Secondary_Contact_Phone_No = '1111111';
       lf3.Secondary_Contact_Job_Title = 'Director';
       
       lf3.Enquiry_Status = 'Accepted';
       lf3.Media_Type = 'Digital';
       
       req.leadsInfo.add(lf3);
       List<DMLLeadWebServiceClass.LeadRecordResponse> dmlRes = new List<DMLLeadWebServiceClass.LeadRecordResponse>();
         dmlRes= DMLLeadWebServiceClass.createLead(req);
         
         
         
         }
       

      
*/
     
     }